language: node_js

node_js:
  - node

cache: yarn

script:
  - yarn ci

deploy:
  edge: true
  provider: npm
  email: accounts@francoisbest.com
  on:
    tags: true
  skip_cleanup: true
  api_key:
    secure: i7xr9fXkiRQp4dGtzhSspXvumej2U301UMCujjgRqakkQkr+ENQl589fs3nqJBaIuqeY9N4DTYDtn56Y3xNA6ivrEvTTUhJndL1+O3y5FBsJubc8bO7+Cqhhz/UP13q+5JBi54v76BajkTDw1p2fgUWyZs51dKlHZkL1Hb/MsU4EkP4Wy3myCIWyl2WBpPXWnGhX8CZwz6rT66b50tQobPaeao6Qm5fEt2m/ZDlAaCPEfwf3DBEbuy7CXWJQuwWAxaAVSGhi38O0ggdAsMFGIKRZoDxq6++Wcy1DjJAb/IFbFVRoa8MUMDTbNWRrb7p0hIWKSOd+2bClgVnfjgPUhRkTi+lJ9L83XGMNoLOYi0WBvAoWLbV5KCEruAsWZAiZInbuYm6DWGxIhy6cGmrZlCAVlntVTqtb+DhfIWvDfxqNxkLd/reY93L3xLfl5l2gnhFoma6HXYxPndO0arq7BuXlV7eUD+GDnMF0YhgeVPXag72qmzTpVjkBn4SMbWavWxk4/tldKlP+onhWZCIZd6k2JA5F1w53yU0SlQONQKVkxMKYZXNDDIQMq8YUud+RYKXO38JRWs+norY+4XdrzLF2fFHHEur6YL1mi2mNnUfz2a4uk/N4/1oK06AtATfYGUGKRby55n0D8VFZiy5F0I73hzA0HEqrmNR/L2YKCa0=

notifications:
  slack:
    rooms:
      secure: uDq04en6Lug//dHdVYA9NIDpGbM90CYB2XDnHb/PqlavgswbZaCizJ7X3Soj24D2ERRs0fSX/bDqQb3CR3gSa8EScwmMTyiBop6lKr3y8u0sDgSY19HDeK72eWqdCauZkUDgVxLhM/Lypl0Wl2QFfehbIA3299zlQzXVHUmAMqH6kRtnu2HwDw9mMCYFvM6LjY33JrfP2/LhQu3WAZOVYxRlzyQWFsVQZjHHbPyzFBu231uspNY6ztRgwOQK68fOrtnUYQ6hZjVI8CdtwashS6fHi3wxX234Er9qp0o16DmmuNXW9D41v3y+cGPNQtcqLWCV+zqRnbI3Say+8/ro3A66jrGWn5zZHhWtCMUdVEQxTU9qNLcorFyCoxyT7EE7CPpT3dRzYRhqQxs64lZzqbmfGiy/47xJn1AZIHjh+H99Q92rivmr93Qo+JZIVAIKAKPYH2/y6k1bvHuXdGKatXYA70ZyIpE/SojQDrtKkPd6yBZY4/alXlH0i1fnYeUtmRQcMLJE0CxHMdQZPH0mpj/9/m4tCsaTIs94W704pr9QJ1QExMo0CtDdy1gceWNyTWk/R1LHwDeGjusRMBxD3GhQ91m1Rs9f7RwIFp2ab5MznAM/mjAckUTnbDOOtF2VB3/dghSsicCJVV9ZE7D+q+NjhmQhetMK04pFqc3LLTs=
    on_success: always
    on_failure: always
    on_error: always
    template:
      - "Build %{result}: %{repository_slug}"
      - Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) on %{branch}
        by %{author} %{result} in %{duration}
