name: CI/CD

on:
  push:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  ci-cd:
    name: CI/CD
    uses: 47ng/workflows/.github/workflows/node-ci-cd.yml@main
    secrets: inherit
